#ARD_HOME=/opt/arduino-1.6.0rc1-zero-r04
#BOARD =mega
#BOARD_SUB =atmega2560
#BOARD=uno

#BOARD=teensy31
#F_CPU=96000000


PORT = /dev/ttyACM0

# And finally, the part that brings everything together for you.
include ../Arduino_Makefile_master/_Makefile.master
